import { StyleSheet } from "react-native";

import { palette } from "@/src/theme/palette";

export const styles = StyleSheet.create({
  content: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  stickySearchBar: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 10,
    backgroundColor: palette.background,
  },
  listWrap: {
    flex: 1,
  },
  restaurantSeparator: {
    height: 14,
  },
  listLoader: {
    paddingTop: 80,
    alignItems: "center",
    justifyContent: "center",
  },
  footerLoader: {
    minHeight: 64,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  footerLoaderText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    color: palette.mutedForeground,
  },
  headerWrap: {
    paddingTop: 2,
    paddingBottom: 16,
  },
  headerCard: {
    borderRadius: 26,
    backgroundColor: palette.surface,
    padding: 12,
    gap: 12,
    shadowColor: "transparent",
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0,
    borderWidth: 1,
    borderColor: "#F7E3EC",
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  filterButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: palette.secondary,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    flexShrink: 0,
    shadowColor: "transparent",
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0,
  },
  filterBadge: {
    position: "absolute",
    top: -2,
    right: -2,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    paddingHorizontal: 4,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.foreground,
    borderWidth: 1,
    borderColor: palette.surface,
  },
  filterBadgeText: {
    fontSize: 9,
    lineHeight: 11,
    fontWeight: "800",
    color: palette.surface,
  },
  searchBar: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    minHeight: 50,
    paddingHorizontal: 12,
    borderRadius: 18,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: "#F2E0EA",
  },
  searchIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF0F6",
  },
  searchInput: {
    flex: 1,
    minHeight: 20,
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "800",
    color: palette.mutedForeground,
    paddingVertical: 0,
    textAlignVertical: "center",
  },
  clearButton: {
    width: 28,
    height: 28,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F6F0F4",
  },
  pressablePressed: {
    opacity: 0.88,
    transform: [{ scale: 0.97 }],
  },
  chipPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.985 }],
  },
  cardPressed: {
    opacity: 0.92,
    transform: [{ scale: 0.985 }],
  },
  filterChip: {
    minHeight: 40,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 13,
    paddingVertical: 10,
    borderRadius: 15,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#F0E6EE",
    shadowColor: "transparent",
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0,
  },
  filterChipActive: {
    backgroundColor: palette.foreground,
    borderColor: palette.foreground,
  },
  filterChipText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    color: palette.foreground,
  },
  filterChipTextActive: {
    color: palette.surface,
  },
  sortRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  sortSummary: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    color: palette.mutedForeground,
  },
  clearFiltersBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: "#F5EFF4",
  },
  clearFiltersBadgeText: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "800",
    color: palette.foreground,
  },
  historyBlock: {
    gap: 10,
  },
  historyLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
    color: palette.foreground,
  },
  recentSearchRow: {
    flexDirection: "row",
    gap: 8,
    paddingRight: 6,
  },
  recentSearchChip: {
    flexDirection: "row",
    alignItems: "center",
    maxWidth: 220,
    flexShrink: 0,
    borderRadius: 999,
    backgroundColor: "#F6F2F8",
  },
  recentSearchMain: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingLeft: 12,
    paddingRight: 6,
    paddingVertical: 9,
  },
  recentSearchText: {
    maxWidth: 150,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    color: palette.foreground,
  },
  recentSearchRemove: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 4,
  },
  recentVisitedRow: {
    paddingRight: 8,
    gap: 12,
  },
  recentVisitedCardWrap: {
    width: 232,
  },
  recentVisitedCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: 22,
    backgroundColor: palette.surface,
    padding: 10,
    borderWidth: 1,
    borderColor: "#F1E2EA",
    shadowColor: "transparent",
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0,
  },
  recentVisitedThumb: {
    width: 64,
    height: 64,
    borderRadius: 18,
    overflow: "hidden",
    backgroundColor: "#F7F1F7",
  },
  recentVisitedImage: {
    width: "100%",
    height: "100%",
  },
  recentVisitedImageFallback: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F7F1F7",
  },
  recentVisitedCopy: {
    flex: 1,
    gap: 3,
  },
  recentVisitedTitle: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
    color: palette.foreground,
  },
  recentVisitedSubtitle: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "600",
    color: palette.mutedForeground,
  },
  recentVisitedMeta: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "700",
    color: "#AA6A87",
  },
  recentVisitedHeart: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F6F1F5",
  },
  recentVisitedHeartActive: {
    backgroundColor: palette.secondary,
  },
  feedbackCard: {
    minHeight: 56,
    paddingHorizontal: 16,
    borderRadius: 24,
    backgroundColor: palette.surface,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  feedbackText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "600",
    color: palette.foreground,
  },
  filterModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(20, 24, 35, 0.32)",
    justifyContent: "center",
    padding: 18,
  },
  filterModalCard: {
    borderRadius: 30,
    backgroundColor: palette.surface,
    padding: 22,
    gap: 18,
    shadowColor: "transparent",
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0,
    borderWidth: 1,
    borderColor: "#E8EDF5",
    overflow: "hidden",
    position: "relative",
  },
  filterAccentOrb: {
    position: "absolute",
    width: 132,
    height: 132,
    borderRadius: 66,
    backgroundColor: "#FCE2EC",
    top: -34,
    right: -26,
  },
  filterModalHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    zIndex: 1,
  },
  filterPill: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "#FFF1F6",
    marginBottom: 12,
  },
  filterPillText: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "800",
    color: "#D85A8A",
  },
  filterModalTitle: {
    fontSize: 22,
    lineHeight: 26,
    fontWeight: "800",
    color: palette.foreground,
  },
  filterModalSubtitle: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "500",
    color: palette.mutedForeground,
    maxWidth: 220,
  },
  filterModalClose: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F3F5FA",
    alignItems: "center",
    justifyContent: "center",
  },
  filterSection: {
    gap: 12,
    padding: 15,
    borderRadius: 24,
    backgroundColor: "#FFFBFD",
    borderWidth: 1,
    borderColor: "#F4E7EE",
    shadowColor: "transparent",
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0,
  },
  filterSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  filterSectionIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF1F6",
  },
  filterSectionLabel: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "800",
    color: palette.foreground,
  },
  filterOptionsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  filterInsightRow: {
    flexDirection: "row",
    gap: 10,
  },
  filterInsightCard: {
    flex: 1,
    minHeight: 70,
    borderRadius: 22,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: "#FFF7FB",
    borderWidth: 1,
    borderColor: "#F1E2EA",
    justifyContent: "center",
    gap: 2,
  },
  filterInsightValue: {
    fontSize: 20,
    lineHeight: 25,
    fontWeight: "900",
    color: palette.foreground,
  },
  filterInsightLabel: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "700",
    color: palette.mutedForeground,
  },
  filterFooter: {
    flexDirection: "row",
    gap: 10,
  },
  filterResetButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 18,
    backgroundColor: "#FFF5EF",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 7,
  },
  filterResetText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
    color: palette.foreground,
  },
  filterApplyButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 20,
    backgroundColor: palette.secondary,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 7,
  },
  filterApplyText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
    color: palette.surface,
  },
});
