import { StyleSheet } from "react-native";

import { palette } from "@/src/theme/palette";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  offscreenPlaceholder: {
    flex: 1,
  },
  buttonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.97 }],
  },
  emptyWrap: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  content: {
    paddingBottom: 160,
    gap: 20,
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 14,
    gap: 6,
  },
  kicker: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
    color: palette.secondary,
  },
  title: {
    fontSize: 32,
    lineHeight: 38,
    fontWeight: "800",
    color: palette.foreground,
  },
  subtitle: {
    fontSize: 15,
    lineHeight: 23,
    fontWeight: "500",
    color: palette.mutedForeground,
  },
  headerStatRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 8,
  },
  infoPill: {
    flex: 1,
    minHeight: 72,
    borderRadius: 18,
    paddingHorizontal: 10,
    paddingVertical: 10,
    justifyContent: "center",
  },
  infoPillTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 4,
  },
  infoPillLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
    color: palette.mutedForeground,
  },
  infoPillValue: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
    color: palette.foreground,
  },
  validationCard: {
    marginHorizontal: 20,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderRadius: 24,
    backgroundColor: palette.surface,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    shadowColor: palette.shadow,
    shadowOpacity: 0.6,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  validationIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.warningSurface,
  },
  validationIconWrapInfo: {
    backgroundColor: "#FFEAF3",
  },
  validationCopy: {
    flex: 1,
    gap: 3,
  },
  validationTitle: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
    color: palette.foreground,
  },
  validationSubtitle: {
    fontSize: 13,
    lineHeight: 19,
    color: palette.mutedForeground,
  },
  validationActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
  },
  validationAction: {
    minHeight: 34,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: palette.surfaceMuted,
    borderWidth: 1,
    borderColor: palette.border,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  validationActionDisabled: {
    opacity: 0.68,
  },
  validationActionPrimary: {
    backgroundColor: palette.secondary,
    borderColor: palette.secondary,
  },
  validationActionText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
    color: palette.foreground,
  },
  validationActionPrimaryText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
    color: palette.surface,
  },
  reorderBadgeCard: {
    marginHorizontal: 20,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderRadius: 24,
    backgroundColor: "#FFEAF3",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    shadowColor: palette.shadow,
    shadowOpacity: 0.35,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  reorderBadgeIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFFCC",
  },
  reorderBadgeCopy: {
    flex: 1,
    gap: 3,
  },
  reorderBadgeTitle: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
    color: palette.foreground,
  },
  reorderBadgeSubtitle: {
    fontSize: 12,
    lineHeight: 18,
    color: palette.mutedForeground,
  },
  reorderBadgeClose: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFFA8",
  },
  restaurantCard: {
    marginHorizontal: 20,
    padding: 20,
    borderRadius: 38,
    backgroundColor: palette.surface,
    gap: 14,
    shadowColor: palette.shadow,
    shadowOpacity: 1,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 14 },
    elevation: 7,
  },
  restaurantCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  restaurantCardCopy: {
    flex: 1,
    gap: 2,
  },
  restaurantName: {
    fontSize: 21,
    lineHeight: 27,
    fontWeight: "800",
    color: palette.foreground,
  },
  restaurantMeta: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
    color: palette.mutedForeground,
  },
  clearButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: palette.surfaceMuted,
  },
  clearButtonText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    color: palette.foreground,
  },
  itemList: {
    gap: 10,
  },
  recommendationSection: {
    marginHorizontal: 20,
    paddingVertical: 13,
    borderRadius: 28,
    backgroundColor: "#FFFDFE",
    borderWidth: 1,
    borderColor: "#F7DFE8",
    gap: 12,
    shadowColor: palette.shadow,
    shadowOpacity: 0.35,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
    overflow: "hidden",
  },
  recommendationHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingHorizontal: 14,
  },
  recommendationTitleWrap: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  recommendationTitle: {
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "800",
    color: palette.foreground,
  },
  recommendationSubtitle: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
    color: palette.mutedForeground,
  },
  recommendationHint: {
    minHeight: 28,
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 6,
    backgroundColor: "#FFEAF3",
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
  },
  recommendationHintText: {
    fontSize: 10,
    lineHeight: 13,
    fontWeight: "800",
    color: palette.secondary,
  },
  recommendationRow: {
    paddingLeft: 14,
    paddingRight: 14,
    gap: 10,
  },
  recommendationCard: {
    width: 110,
    borderRadius: 22,
    backgroundColor: "#FFFFFF",
  },
  recommendationCardPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.97 }],
  },
  recommendationImage: {
    width: "100%",
    height: 110,
    borderRadius: 22,
    overflow: "hidden",
    backgroundColor: "#F3E6DE",
  },
  recommendationCopy: {
    minHeight: 39,
    paddingTop: 7,
    paddingHorizontal: 2,
    gap: 2,
  },
  recommendationName: {
    fontSize: 11.5,
    lineHeight: 14,
    fontWeight: "800",
    color: palette.foreground,
  },
  recommendationPrice: {
    fontSize: 10.5,
    lineHeight: 13,
    fontWeight: "800",
    color: palette.secondary,
  },
  recommendationAction: {
    position: "absolute",
    top: 7,
    right: 7,
    width: 29,
    height: 29,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.secondary,
    shadowColor: "rgba(255,99,146,0.32)",
    shadowOpacity: 1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  recommendationPopularIcon: {
    position: "absolute",
    top: 7,
    left: 7,
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,99,146,0.94)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.8)",
  },
  recommendationEndSpacer: {
    width: 1,
  },
  addMoreButton: {
    marginTop: 8,
    alignSelf: "flex-start",
    minHeight: 38,
    borderRadius: 999,
    paddingHorizontal: 13,
    paddingVertical: 8,
    backgroundColor: "#FFF4F8",
    borderWidth: 1,
    borderColor: "rgba(255, 43, 133, 0.22)",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  addMoreButtonPressed: {
    opacity: 0.82,
    backgroundColor: "#FFE9F1",
  },
  addMoreButtonText: {
    fontSize: 13,
    fontWeight: "700",
    color: palette.secondary,
  },
  itemRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    padding: 10,
    borderRadius: 24,
    backgroundColor: palette.surfaceMuted,
  },
  itemImage: {
    width: 74,
    height: 74,
    flexShrink: 0,
    borderRadius: 18,
    backgroundColor: palette.surface,
  },
  itemFallback: {
    width: 74,
    height: 74,
    flexShrink: 0,
    borderRadius: 18,
    backgroundColor: palette.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  itemMain: {
    flex: 1,
    minWidth: 0,
    gap: 10,
  },
  itemHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  itemTitleBlock: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  itemName: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
    color: palette.foreground,
  },
  itemMeta: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
    color: palette.mutedForeground,
  },
  itemMetaBlock: {
    gap: 2,
    marginTop: -4,
  },
  itemFooterRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 12,
  },
  itemPriceBlock: {
    flexShrink: 1,
    minWidth: 0,
    gap: 2,
  },
  itemPriceRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 6,
  },
  itemPriceStrike: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
    color: palette.mutedForeground,
    textDecorationLine: "line-through",
  },
  itemLineTotal: {
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "800",
    color: palette.foreground,
  },
  itemUnitCaption: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "600",
    color: palette.mutedForeground,
  },
  itemOfferPill: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: palette.successSurface,
  },
  itemOfferPillText: {
    fontSize: 10,
    lineHeight: 13,
    fontWeight: "800",
    color: palette.successText,
  },
  itemPriceChanged: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "700",
    color: palette.secondary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  quantityControl: {
    width: 96,
    height: 36,
    paddingHorizontal: 4,
    borderRadius: 999,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FFEAF3",
    overflow: "visible",
  },
  quantityButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surface,
    overflow: "visible",
  },
  quantityButtonPrimary: {
    backgroundColor: palette.secondary,
  },
  quantityButtonPressed: {
    opacity: 0.86,
    transform: [{ scale: 0.94 }],
  },
  quantityButtonSecondaryPressed: {
    backgroundColor: "#FFEAF3",
  },
  quantityText: {
    minWidth: 20,
    textAlign: "center",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
    color: palette.foreground,
  },
  removeText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    color: palette.primary,
  },
  summaryCard: {
    marginHorizontal: 20,
    padding: 20,
    borderRadius: 38,
    backgroundColor: palette.surface,
    gap: 10,
    shadowColor: palette.shadow,
    shadowOpacity: 1,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  offerProgressCard: {
    marginBottom: 14,
    padding: 14,
    borderRadius: 24,
    backgroundColor: palette.surfaceMuted,
    gap: 8,
  },
  offerProgressCardUnlocked: {
    backgroundColor: palette.successSurface,
  },
  offerProgressHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  offerProgressBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  offerProgressBadgeText: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "700",
    color: palette.secondary,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  offerProgressBadgeTextUnlocked: {
    color: palette.successText,
  },
  offerProgressValue: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    color: palette.foreground,
  },
  offerProgressSubtitle: {
    fontSize: 13,
    lineHeight: 18,
    color: palette.mutedForeground,
  },
  offerTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: "#F3DDCC",
    overflow: "hidden",
  },
  offerFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: palette.secondary,
  },
  offerFillUnlocked: {
    backgroundColor: palette.successText,
  },
  summaryTitle: {
    fontSize: 21,
    lineHeight: 27,
    fontWeight: "800",
    color: palette.foreground,
    marginBottom: 2,
  },
  summaryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  summaryLabel: {
    fontSize: 15,
    lineHeight: 23,
    fontWeight: "500",
    color: palette.mutedForeground,
  },
  summaryValue: {
    fontSize: 15,
    lineHeight: 23,
    fontWeight: "500",
    color: palette.foreground,
  },
  summaryHighlight: {
    color: palette.successText,
  },
  summaryStrong: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
    color: palette.foreground,
  },
  divider: {
    height: 1,
    backgroundColor: palette.border,
    marginVertical: 2,
  },
  checkoutWrap: {
    position: "absolute",
    left: 20,
    right: 20,
    bottom: 0,
  },
  checkoutCard: {
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 38,
    backgroundColor: palette.secondary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
    shadowColor: palette.shadow,
    shadowOpacity: 1,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 14 },
    elevation: 7,
  },
  checkoutCopy: {
    flex: 1,
    gap: 2,
  },
  checkoutLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
    color: "rgba(255,255,255,0.82)",
  },
  checkoutAmount: {
    fontSize: 21,
    lineHeight: 27,
    fontWeight: "800",
    color: "#fff",
  },
  checkoutButtonLift: {
    borderRadius: 999,
    shadowColor: "#111827",
    shadowOpacity: 0.2,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 7 },
    elevation: 5,
  },
  checkoutButtonLiftDisabled: {
    shadowOpacity: 0,
    elevation: 0,
  },
  checkoutButton: {
    minWidth: 164,
    height: 44,
    overflow: "hidden",
    paddingHorizontal: 16,
    borderRadius: 999,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: palette.surface,
  },
  checkoutButtonDisabled: {
    opacity: 0.72,
  },
  checkoutButtonSheen: {
    position: "absolute",
    left: 16,
    right: 16,
    top: 1,
    height: 1,
    backgroundColor: "rgba(255,255,255,0.9)",
  },
  checkoutButtonText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
    color: palette.secondary,
  },
  checkoutButtonSpinner: {
    marginLeft: -2,
  },
});
