import { StyleSheet } from "react-native";

import { palette } from "@/src/theme/palette";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  buttonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.97 }],
  },
  emptyWrap: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  content: {
    paddingBottom: 160,
    gap: 20,
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 14,
    gap: 6,
  },
  kicker: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
    color: palette.secondary,
  },
  title: {
    fontSize: 32,
    lineHeight: 38,
    fontWeight: "800",
    color: palette.foreground,
  },
  subtitle: {
    fontSize: 15,
    lineHeight: 23,
    fontWeight: "500",
    color: palette.mutedForeground,
  },
  headerStatRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 8,
  },
  infoPill: {
    flex: 1,
    minHeight: 72,
    borderRadius: 18,
    paddingHorizontal: 10,
    paddingVertical: 10,
    justifyContent: "center",
  },
  infoPillTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 4,
  },
  infoPillLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
    color: palette.mutedForeground,
  },
  infoPillValue: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
    color: palette.foreground,
  },
  validationCard: {
    marginHorizontal: 20,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderRadius: 24,
    backgroundColor: palette.surface,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    shadowColor: palette.shadow,
    shadowOpacity: 0.6,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  validationIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.warningSurface,
  },
  validationIconWrapInfo: {
    backgroundColor: "#FFEAF3",
  },
  validationCopy: {
    flex: 1,
    gap: 3,
  },
  validationTitle: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
    color: palette.foreground,
  },
  validationSubtitle: {
    fontSize: 13,
    lineHeight: 19,
    color: palette.mutedForeground,
  },
  validationActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
  },
  validationAction: {
    minHeight: 34,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: palette.surfaceMuted,
    borderWidth: 1,
    borderColor: palette.border,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  validationActionDisabled: {
    opacity: 0.68,
  },
  validationActionPrimary: {
    backgroundColor: palette.secondary,
    borderColor: palette.secondary,
  },
  validationActionText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
    color: palette.foreground,
  },
  validationActionPrimaryText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
    color: palette.surface,
  },
  reorderBadgeCard: {
    marginHorizontal: 20,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderRadius: 24,
    backgroundColor: "#FFEAF3",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    shadowColor: palette.shadow,
    shadowOpacity: 0.35,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  reorderBadgeIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFFCC",
  },
  reorderBadgeCopy: {
    flex: 1,
    gap: 3,
  },
  reorderBadgeTitle: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
    color: palette.foreground,
  },
  reorderBadgeSubtitle: {
    fontSize: 12,
    lineHeight: 18,
    color: palette.mutedForeground,
  },
  reorderBadgeClose: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFFA8",
  },
  restaurantCard: {
    marginHorizontal: 20,
    padding: 20,
    borderRadius: 38,
    backgroundColor: palette.surface,
    gap: 14,
    shadowColor: palette.shadow,
    shadowOpacity: 1,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 14 },
    elevation: 7,
  },
  restaurantCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  restaurantCardCopy: {
    flex: 1,
    gap: 2,
  },
  restaurantName: {
    fontSize: 21,
    lineHeight: 27,
    fontWeight: "800",
    color: palette.foreground,
  },
  restaurantMeta: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
    color: palette.mutedForeground,
  },
  clearButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: palette.surfaceMuted,
  },
  clearButtonText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    color: palette.foreground,
  },
  itemList: {
    gap: 10,
  },
  recommendationSection: {
    // Nested INSIDE the cart's restaurantCard (below "Add more"). A subtle hairline on top separates
    // the recommendations from the cart items + "Add more" group above, without becoming a card.
    gap: 10,
    marginTop: 4,
    paddingTop: 15,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(31,36,48,0.09)",
  },
  recommendationHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  recommendationTitleWrap: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  recommendationTitle: {
    fontSize: 13.5,
    lineHeight: 18,
    fontWeight: "800",
    color: palette.foreground,
  },
  recommendationSubtitle: {
    fontSize: 11.5,
    lineHeight: 15,
    fontWeight: "600",
    color: palette.mutedForeground,
  },
  recommendationHint: {
    minHeight: 28,
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 6,
    backgroundColor: "#FFEAF3",
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
  },
  recommendationHintText: {
    fontSize: 10,
    lineHeight: 13,
    fontWeight: "800",
    color: palette.secondary,
  },
  recommendationRow: {
    // No left padding — the parent restaurantCard already insets by 20, so card 1 lines up with the
    // cart items and the "Add more" button above it.
    paddingRight: 4,
    gap: 10,
  },
  recommendationCard: {
    // width is set inline (measured for a 3-card + peek layout) — see recommendationCardWidth.
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
  },
  recommendationCardPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.97 }],
  },
  // Relative wrapper so the flame/plus overlays sit OVER the image as siblings — the image
  // itself stays a plain self-closing RemoteImage (passing overlays as RemoteImage children
  // left the photo blank; every other image in the app uses this sibling pattern).
  recommendationMedia: {
    width: "100%",
    position: "relative",
  },
  recommendationImage: {
    width: "100%",
    height: 84,
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: "#F3E6DE",
  },
  recommendationCopy: {
    minHeight: 33,
    paddingTop: 6,
    paddingHorizontal: 1,
    gap: 1,
  },
  recommendationName: {
    fontSize: 11,
    lineHeight: 13.5,
    fontWeight: "800",
    color: palette.foreground,
  },
  recommendationPrice: {
    fontSize: 10.5,
    lineHeight: 13,
    fontWeight: "800",
    color: palette.secondary,
  },
  recommendationAction: {
    position: "absolute",
    top: 6,
    right: 6,
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.secondary,
    shadowColor: "rgba(255,99,146,0.32)",
    shadowOpacity: 1,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  recommendationPopularIcon: {
    position: "absolute",
    top: 6,
    left: 6,
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,99,146,0.94)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.8)",
  },
  recommendationEndSpacer: {
    width: 1,
  },
  // The scale/press feedback lives on the PressableScale wrapper; the alignment + the
  // "pull up close to the cart items" margin sit on that outer slot so the % / auto width
  // resolves correctly (the restaurantCard's gap:14 otherwise stranded it).
  addMoreButtonSlot: {
    marginTop: -5,
    alignSelf: "flex-start",
  },
  addMoreButton: {
    minHeight: 38,
    borderRadius: 999,
    paddingHorizontal: 13,
    paddingVertical: 8,
    backgroundColor: "#FFF4F8",
    borderWidth: 1,
    borderColor: "rgba(255, 43, 133, 0.22)",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  addMoreButtonText: {
    fontSize: 13,
    fontWeight: "700",
    color: palette.secondary,
  },
  itemRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    padding: 10,
    borderRadius: 24,
    backgroundColor: palette.surfaceMuted,
  },
  itemImage: {
    width: 74,
    height: 74,
    flexShrink: 0,
    borderRadius: 18,
    backgroundColor: palette.surface,
  },
  itemFallback: {
    width: 74,
    height: 74,
    flexShrink: 0,
    borderRadius: 18,
    backgroundColor: palette.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  itemMain: {
    flex: 1,
    minWidth: 0,
    gap: 10,
  },
  itemHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  itemTitleBlock: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  itemName: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
    color: palette.foreground,
  },
  itemMeta: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
    color: palette.mutedForeground,
  },
  itemMetaBlock: {
    gap: 2,
    marginTop: -4,
  },
  itemFooterRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 12,
  },
  itemPriceBlock: {
    flexShrink: 1,
    minWidth: 0,
    gap: 2,
  },
  itemPriceRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 6,
  },
  itemPriceStrike: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
    color: palette.mutedForeground,
    textDecorationLine: "line-through",
  },
  itemLineTotal: {
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "800",
    color: palette.foreground,
  },
  itemUnitCaption: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "600",
    color: palette.mutedForeground,
  },
  itemOfferPill: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: palette.successSurface,
  },
  itemOfferPillText: {
    fontSize: 10,
    lineHeight: 13,
    fontWeight: "800",
    color: palette.successText,
  },
  itemPriceChanged: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "700",
    color: palette.secondary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  quantityControl: {
    width: 96,
    height: 36,
    paddingHorizontal: 4,
    borderRadius: 999,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FFEAF3",
    overflow: "visible",
  },
  quantityButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surface,
    overflow: "visible",
  },
  quantityButtonPrimary: {
    backgroundColor: palette.secondary,
  },
  quantityButtonPressed: {
    opacity: 0.86,
    transform: [{ scale: 0.94 }],
  },
  quantityButtonSecondaryPressed: {
    backgroundColor: "#FFEAF3",
  },
  quantityText: {
    minWidth: 20,
    textAlign: "center",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
    color: palette.foreground,
  },
  removeText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    color: palette.primary,
  },
  summaryCard: {
    marginHorizontal: 20,
    padding: 20,
    borderRadius: 38,
    backgroundColor: palette.surface,
    gap: 10,
    shadowColor: palette.shadow,
    shadowOpacity: 1,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  // Dark-neon "reward progress" card — same visual family as the urgent-delivery priority
  // sticker (NeonStickerCard). Amber accent while the offer is still locked, switching to
  // green the moment it unlocks (border + shadow + badge + progress fill all recolour).
  offerProgressCard: {
    marginBottom: 14,
    padding: 14,
    borderRadius: 22,
    backgroundColor: "#211A2E",
    borderWidth: 1,
    borderColor: "rgba(255, 201, 77, 0.35)",
    gap: 8,
    shadowColor: "#FFC94D",
    shadowOpacity: 0.3,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  offerProgressCardUnlocked: {
    borderColor: "rgba(53, 214, 164, 0.4)",
    shadowColor: "#35D6A4",
  },
  offerProgressHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  offerProgressHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    flexShrink: 0,
  },
  offerProgressPressed: {
    opacity: 0.92,
    transform: [{ scale: 0.995 }],
  },
  offerProgressBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    flexShrink: 1,
    minWidth: 0,
  },
  // Accent icon tile that echoes the priority sticker's glowing badge.
  offerProgressBadgeIcon: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFC94D",
  },
  offerProgressBadgeIconUnlocked: {
    backgroundColor: "#35D6A4",
  },
  offerProgressBadgeText: {
    flexShrink: 1,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "800",
    color: "#FFC94D",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  offerProgressBadgeTextUnlocked: {
    color: "#35D6A4",
  },
  offerProgressValue: {
    flexShrink: 0,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
    color: "#FFFFFF",
    fontVariant: ["tabular-nums"],
  },
  offerProgressSubtitle: {
    marginTop: 6,
    fontSize: 13,
    lineHeight: 18,
    color: "#C9C2D6",
  },
  offerTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: "rgba(255, 255, 255, 0.14)",
    overflow: "hidden",
  },
  offerFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#FFC94D",
  },
  offerFillUnlocked: {
    backgroundColor: "#35D6A4",
  },
  summaryTitle: {
    fontSize: 21,
    lineHeight: 27,
    fontWeight: "800",
    color: palette.foreground,
    marginBottom: 2,
  },
  summaryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  summaryLabel: {
    fontSize: 15,
    lineHeight: 23,
    fontWeight: "500",
    color: palette.mutedForeground,
  },
  summaryValue: {
    fontSize: 15,
    lineHeight: 23,
    fontWeight: "500",
    color: palette.foreground,
  },
  summaryHighlight: {
    color: palette.successText,
  },
  // Right-aligned stack for the delivery fee: base fee on top, the "+extra" surcharge under it.
  summaryDeliveryValueStack: {
    alignItems: "flex-end",
  },
  // The "+extra" surcharge that sits UNDER the base delivery fee — small + muted so the base fee
  // stays the headline number and the surcharge reads as a quiet add-on.
  summaryDeliveryExtra: {
    marginTop: -2,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "600",
    color: palette.mutedForeground,
  },
  // Sits directly under the "Delivery fee" row (the summaryCard gap is 10, so the negative top
  // margin overcancels it and tucks this caption snug under the fee) — explains WHY the fee is what it is.
  summaryDeliveryNote: {
    marginTop: -14,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    color: palette.mutedForeground,
  },
  // Optional platform-fee opt-in control (tappable row with a check box on the right).
  platformFeeOptInRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: palette.border,
    backgroundColor: palette.surfaceMuted,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  platformFeeOptInCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  platformFeeOptInLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: palette.foreground,
  },
  platformFeeOptInNote: {
    fontSize: 12,
    lineHeight: 16,
    color: palette.mutedForeground,
  },
  platformFeeCheck: {
    width: 22,
    height: 22,
    borderRadius: 7,
    borderWidth: 1.5,
    borderColor: palette.border,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surface,
  },
  platformFeeCheckOn: {
    backgroundColor: palette.secondary,
    borderColor: palette.secondary,
  },
  summaryStrong: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
    color: palette.foreground,
  },
  divider: {
    height: 1,
    backgroundColor: palette.border,
    marginVertical: 2,
  },
  checkoutWrap: {
    position: "absolute",
    left: 20,
    right: 20,
    bottom: 0,
  },
  // A prominent full-width amber banner (not a tiny centred pill) so the "you can't
  // check out yet" nudge is impossible to miss, with an icon tile + a small progress bar
  // showing how close the cart is to the minimum.
  minimumOrderNotice: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    marginBottom: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 18,
    backgroundColor: palette.warningSurface,
    borderWidth: 1.5,
    borderColor: "rgba(231, 139, 39, 0.5)",
  },
  minimumOrderNoticeIcon: {
    width: 32,
    height: 32,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(231, 139, 39, 0.18)",
  },
  minimumOrderNoticeCopy: {
    flex: 1,
    gap: 8,
  },
  minimumOrderNoticeText: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "800",
    color: palette.warningText,
  },
  minimumOrderTrack: {
    height: 6,
    borderRadius: 999,
    backgroundColor: "rgba(231, 139, 39, 0.2)",
    overflow: "hidden",
  },
  minimumOrderFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: palette.warningText,
  },
  checkoutCard: {
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 38,
    backgroundColor: palette.secondary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
    shadowColor: palette.shadow,
    shadowOpacity: 1,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 14 },
    elevation: 7,
  },
  checkoutCopy: {
    flex: 1,
    gap: 2,
  },
  checkoutLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
    color: "rgba(255,255,255,0.82)",
  },
  checkoutAmount: {
    fontSize: 21,
    lineHeight: 27,
    fontWeight: "800",
    color: "#fff",
  },
  checkoutButtonLift: {
    borderRadius: 999,
    shadowColor: "#111827",
    shadowOpacity: 0.2,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 7 },
    elevation: 5,
  },
  checkoutButtonLiftDisabled: {
    shadowOpacity: 0,
    elevation: 0,
  },
  checkoutButton: {
    minWidth: 164,
    height: 44,
    overflow: "hidden",
    paddingHorizontal: 16,
    borderRadius: 999,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: palette.surface,
  },
  checkoutButtonDisabled: {
    opacity: 0.72,
  },
  checkoutButtonSheen: {
    position: "absolute",
    left: 16,
    right: 16,
    top: 1,
    height: 1,
    backgroundColor: "rgba(255,255,255,0.9)",
  },
  checkoutButtonText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
    color: palette.secondary,
  },
  checkoutButtonSpinner: {
    marginLeft: -2,
  },
});
