export const palette = {
  background: "#FFF7EF",
  surface: "#FFFFFF",
  surfaceMuted: "#FFF3E9",
  foreground: "#1F2430",
  mutedForeground: "#6F7285",
  border: "#F3DDCC",
  // Brand accent is pink (no orange anywhere). primaryStrong stays near-black for dark
  // buttons/text, so the app reads as pink + black + white.
  primary: "#FF6392",
  primarySoft: "#FFF1F6",
  primaryStrong: "#1F2430",
  secondary: "#FF6392",
  success: "#14985B",
  successSoft: "#EFFAF5",
  successSurface: "#EFFAF5",
  successText: "#14985B",
  warning: "#E78B27",
  warningSoft: "#FFF6E3",
  warningSurface: "#FFF6E3",
  warningText: "#E78B27",
  danger: "#B42318",
  dangerSoft: "#FFE8E5",
  info: "#5D8BFF",
  infoSoft: "#EAF0FF",
  sky: "#5D8BFF",
  mint: "#38C7A3",
  lime: "#B6D957",
  amber: "#FFC857",
  placeholder: "#9CA3AF",
  heroBackground: "#FFFFFF",
  heroOrbPrimary: "#FFC2D6",
  heroOrbSecondary: "#FF99B5",
  heroAccentText: "#B4245C",
  shadow: "rgba(31, 36, 48, 0.12)",
} as const;
