import { useMemo } from "react";

import {
  usePreferencesStore,
  type AppLanguage,
} from "@/src/store/preferences-store";

const copy = {
  en: {
    tabs: {
      available: "Available",
      active: "Active",
      map: "Map",
      history: "History",
      profile: "Profile",
      home: "Home",
      myRides: "My Rides",
      account: "Account",
      notifications: "Notifications",
    },
    bootstrap: {
      text: "Preparing your rider workspace...",
    },
    common: {
      online: "Online",
      offline: "Offline",
      language: "Language",
      refresh: "Refresh",
      retry: "Retry",
      signOut: "Sign out",
      allTime: "All time",
      today: "Today",
      last7Days: "Last 7 days",
      allStatus: "All status",
      delivered: "Delivered",
      cancelled: "Cancelled",
      customer: "Customer",
      restaurant: "Restaurant",
      urgent: "Urgent",
    },
    map: {
      eyebrow: "Live pickup map",
      activeRestaurants: (count: number) =>
        `${count} active restaurant${count === 1 ? "" : "s"}`,
      noActivePickup: "No active pickup",
      zoomIn: "Zoom in",
      zoomOut: "Zoom out",
      focusRider: "Focus rider",
      nextRoute: "Next route",
      readyOnly: "Ready only",
      loadingMap: "Loading rider map...",
      preparingMap: "Preparing pickup map",
      loadingStates: "Loading restaurants and order states...",
      previewing: (name: string) => `Previewing: ${name}`,
      dropOffFirst: (name: string) => `Drop-off first: ${name}`,
      suggestedNext: (name: string) => `Suggested next: ${name}`,
      distanceAway: (state: string, distance: string) =>
        `${state} - ${distance} away`,
      noActiveNearby: "No active pickup nearby",
      emptyHint: "Accepted, preparing, or ready orders will appear here.",
      restaurantLocation: "Restaurant location",
      reachCustomer: "Reach customer",
      reachRestaurant: "Reach restaurant",
      customerRoute: "Customer route",
      orders: "Orders",
      nextReady: "Next ready",
      readyCount: (count: number) => `${count} ready`,
      lateCount: (count: number) => `${count} late`,
      planAhead: "Plan ahead",
      orderStates: "Order states",
      switchRestaurantHint: "Tap map markers to switch restaurant",
      previewRoute: "Preview route",
      openDirections: "Open directions",
      noOrderSelected: "No order selected",
      readyNow: "Ready now",
      pickedUp: "Picked up",
      preparing: "Preparing",
      almostReady: "Almost ready",
      minute: "1 min",
      minutes: (count: number) => `${count} min`,
      minutesLate: (count: number) => `${count} min late`,
      minutesLeft: (count: number) => `${count} min left`,
      distanceMeters: (meters: number) => `${meters} m`,
      distanceKm: (km: string) => `${km} km`,
      statusReady: "Ready",
      statusPickedUp: "Picked up",
      statusPreparing: "Preparing",
      statusAccepted: "Accepted",
      statusFallback: "Order",
    },
    signIn: {
      kicker: "Foodbela Rider",
      title: "Sign in with your phone",
      subtitle:
        "Use your rider phone number to access ready pickups, active trips, and live tracking.",
      phoneLabel: "Phone number",
      phonePlaceholder: "01XXXXXXXXX",
      nameLabel: "Full name (Optional)",
      namePlaceholder: "Rider name",
      sendOtp: "Send OTP",
      sendOtpError: "Unable to send OTP.",
    },
    verify: {
      title: "Verify your rider OTP",
      subtitle: (phone: string) => `Enter the 4-digit code sent to ${phone}.`,
      placeholder: "1234",
      action: "Verify and continue",
      error: "Unable to verify OTP.",
    },
    active: {
      title: "Active trips",
      subtitle: "Pickup and delivery orders currently assigned to you.",
      emptyTitle: "No active trips",
      emptyText: "Pick up a ready order to start live tracking.",
      searchPlaceholder: "Search active trips",
      noMatchingTitle: "No matching trips",
      noMatchingText: "Try another search to find the trip you need.",
      tripsCount: (count: number) =>
        `${count} ${count === 1 ? "active trip" : "active trips"}`,
    },
    available: {
      title: "Ready for pickup",
      subtitle: "Orders waiting for a cycle rider.",
      emptyTitle: "No pickups right now",
      emptyOnline: "New ready orders will show up here automatically.",
      emptyOffline:
        "You are offline. Go online from Profile to receive new pickup orders.",
      locationPending: "Customer location pending",
      searchPlaceholder: "Search pickups",
      noMatchingTitle: "No matching pickups",
      noMatchingText: "Try another search to find a pickup faster.",
      pickupsCount: (count: number) =>
        `${count} ${count === 1 ? "pickup" : "pickups"}`,
    },
    history: {
      title: "Completed history",
      subtitle: "Review past trips, filters, and recent delivery activity.",
      delivered: "Delivered",
      cancelled: "Cancelled",
      earnings: "Trips",
      noTripsTitle: "No trips for this filter",
      noTripsText:
        "Try another status or date range to see your completed deliveries.",
      earningLine: "Customer",
      searchPlaceholder: "Search orders",
      filterTitle: "Filter trips",
      filterButton: "Filter",
      filterStatus: "Status",
      filterTimeRange: "Time range",
      thisMonth: "This month",
      last30Days: "Last 30 days",
      clear: "Clear",
      reset: "Reset",
      done: "Done",
      applyFilters: "Apply filters",
      noMatchingTitle: "No matching trips",
      noMatchingText: "Try another search or adjust your filters.",
      tripsCount: (count: number) =>
        `${count} ${count === 1 ? "trip" : "trips"}`,
    },
    profile: {
      title: "Rider profile",
      today: "Today",
      last7Days: "Last 7 days",
      delivered: "completed",
      vehicle: "Vehicle",
      riderStatus: "Rider status",
      liveTrip: "Live trip",
      noActiveLiveTrip: "No active live trip",
      activeAssignedOrders: "Active assigned orders",
      toggleTitle: "Accept new assignments",
      toggleDescription:
        "Go online to receive rider assignments. Offline riders stay hidden from assignment flow and live map.",
      toggleHint: "You are currently offline for dispatching.",
      toggleWarning:
        "Finish your active assigned orders before switching offline.",
      languageTitle: "Language",
      locationPermissionTitle: "Location permission needed",
      locationPermissionText:
        "Allow location when going online so dispatch can place you on the map and route orders correctly.",
      statusUpdateFailed: "Status update failed",
      statusUpdateFailedText: "Unable to update rider status.",
    },
    riderSocket: {
      assignmentUpdated: "Assignment updated",
      newAssignment: "New assignment",
      assignmentChanged: "Your delivery assignment has changed.",
      viewOrder: "View order",
      okay: "Okay",
    },
    orderDetails: {
      unavailable: "Order details are not available right now.",
      acceptFailed: "Accept failed",
      pickupFailed: "Pickup failed",
      deliverFailed: "Delivery update failed",
      trackingSwitchFailed: "Live trip switch failed",
      acceptFailedText: "Unable to accept order.",
      pickupFailedText: "Unable to pick up order.",
      deliverFailedText: "Unable to complete delivery.",
      trackingSwitchFailedText: "Unable to switch active live tracking.",
      acceptOrder: "Accept order",
      pickUpOrder: "Pick up order",
      makeLiveTrip: "Make this the live trip",
      holdToDeliver: "Press and hold to mark delivered",
      deliveringNow: "Delivering now",
      inQueue: "In queue",
      startThisDelivery: "Start this delivery",
      queuedDeliverLocked:
        "This delivery is in queue. Finish your current delivery, or start this one to deliver it now.",
      switchDeliveryTitle: "Switch live delivery?",
      switchDeliveryBody:
        "This order becomes your live delivery and its customer sees you on the map. Your current delivery goes back to the queue.",
      switchDeliveryConfirm: "Start delivery",
      switchDeliveryCancel: "Cancel",
      switchDeliveryFailed: "Could not switch delivery. Please try again.",
      callCustomer: "Call customer",
      callRestaurant: "Call restaurant",
      previewTitle: "Preview mode",
      previewText:
        "Make this the live trip to see the current approach leg and live ETA for this order.",
      availableToAccept: "Available to accept",
      liveTripActive: "Live trip active",
      assignedToYou: "Assigned to you",
      routeHintPreview:
        "Preview only. Restaurant and customer drop are visible, but the live approach leg belongs to your active trip.",
      routeHintPickedUp:
        "Customer drop stays active, and the restaurant-to-home leg remains visible for full trip context.",
      routeHintAssigned:
        "Pickup is the active leg. Restaurant, rider and customer drop are all visible together.",
      routeHintDefault: "Accept this order to start the pickup leg.",
      customerTitle: "Customer",
      restaurantTitle: "Restaurant",
      itemsTitle: "Items",
      timelineTitle: "Timeline",
      currentPickupLeg: "Current pickup leg",
      currentDeliveryLeg: "Current delivery leg",
      nextDeliveryLeg: "Next delivery leg after pickup",
      routeContext: "Restaurant to home context",
      fullTripEstimate: "Full trip estimate",
      toCustomer: "To customer",
      toRestaurant: "To restaurant",
      openInMaps: "Open in Google Maps",
      sharingLive: "Live location is being shared",
      tripEta: "Trip ETA",
      dropAfterPickup: "Drop after pickup",
      previewDistance: "Preview",
      activateToSeeLiveApproach: "Activate to see live approach",
      fullTripDropMeta: "This is the remaining time to complete the drop.",
      fullTripPickupMeta: "Includes pickup leg and customer delivery leg.",
      syncLive: "Live tracking synced",
      syncSyncing: "Syncing rider location",
      syncOffline: "Tracking paused, retrying",
      lastSync: (value: string) => `Last sync ${value}`,
      queuedWaiting: (count: number) =>
        count > 0
          ? `${count} location update waiting to send`
          : "Sending the latest rider location now",
      queuedRetry: (count: number) =>
        `${count} queued update${count === 1 ? "" : "s"} will be retried automatically`,
      trackingWeakConnection:
        "Connection is weak. Live delivery updates will resume automatically.",
      trackingPermissionError:
        "Location permission is required for live delivery tracking.",
      trackingWaitingFirstLocation:
        "Waiting for the first live location from this device.",
      trackingStartError: "Live location could not be started on this device.",
      pickupSavedWaiting:
        "Pickup saved. Waiting for the first live location from this device.",
      riderLocationWarning:
        "Turn on rider location while online to see your live approach to the restaurant before pickup.",
      warningOfflineAccept:
        "You are offline. Go online from Profile before accepting a new order.",
    },
    sheet: {
      pullUpForDetails: "Pull up for details",
      pullUpToAccept: "Pull up to accept a delivery",
      newOffers: (n: number) => `${n} new ${n === 1 ? "offer" : "offers"}`,
      activeDeliveries: (n: number) => `${n} active ${n === 1 ? "delivery" : "deliveries"}`,
      youreOnline: "You’re online",
      waitingForOrders: "Waiting for new orders…",
      youreOffline: "You’re offline",
      goOnlineReceive: "Go online from the menu to receive orders",
      goOnlineStart: "Go online from the menu to start receiving delivery offers.",
      newOffersTitle: "New offers",
      yourDeliveries: "Your deliveries",
      noOrdersTitle: "No orders right now",
      noOrdersText: "New offers will appear here. Stay online to keep receiving deliveries.",
      distance: "DISTANCE",
      eta: "ETA",
      collect: "COLLECT",
      amount: "AMOUNT",
      timeline: "Timeline",
      items: "Items",
      navigate: "Navigate",
      navigateToRestaurant: "Navigate to restaurant",
      setLive: "Set live",
      open: "Open",
      accept: "Accept",
      acceptDelivery: "Accept delivery",
      markPickedUp: "Mark picked up",
      markDelivered: "Mark delivered",
      cantDeliver: "Can’t deliver this order?",
      orderAmount: "Order amount",
      collectFromCustomer: "Collect from customer",
      assignedAgo: (ago: string) => `Assigned ${ago}`,
      justNow: "just now",
      minAgo: (m: number) => (m === 1 ? "1 min ago" : `${m} min ago`),
      hoursAgo: (h: number, m: number) => `${h}h ${m}m ago`,
      veryLate: (m: number) => `Very late — ${m} min late, deliver now`,
      pickupLate: (m: number) => `Pickup is ${m} min late — head to the restaurant`,
      deliveryLate: (m: number) => `Delivery is ${m} min late — reach the customer soon`,
      veryLateChip: (m: number) => `Very late ${m}m`,
      pickupLateChip: (m: number) => `Pickup ${m}m late`,
      deliveryLateChip: (m: number) => `Delivery ${m}m late`,
      readyInMin: (m: number) => `Ready in ~${m} min`,
      readyAnyMoment: "Ready any moment",
      preparing: "Preparing",
      stillPreparing:
        "Still being prepared — it’ll move to your tasks once it’s ready to pick up.",
      notAssignedYet: "This order isn’t assigned to you yet.",
      cantDeliverSubtitle:
        "Tell us what happened. The customer and support team are notified, and any refund is handled automatically.",
      reasonNoResponse: "Customer did not respond",
      reasonWrongItem: "Wrong item from restaurant",
      reasonOther: "Other reason",
      addNote: "Add a note (optional)",
      keepDelivering: "Keep delivering",
      submit: "Submit",
      confirmPickupTitle: "Confirm pickup",
      confirmPickupBody: (order: string, rest: string) =>
        `Mark ${order} picked up from ${rest}?`,
      yesPickedUp: "Yes, picked up",
      confirmDeliveryTitle: "Confirm delivery",
      confirmDeliveryBody: (order: string) => `Mark ${order} delivered to the customer?`,
      yesDelivered: "Yes, delivered",
      cancel: "Cancel",
      somethingWrong: "Something went wrong",
      tryAgain: "Please try again.",
    },
    notif: {
      eyebrow: "Rider inbox",
      title: "Notifications",
      readAll: "Read all",
      emptyTitle: "No notifications yet",
      emptyText: "Assignment alerts and admin messages will appear here.",
      justNow: "Just now",
      chipLate: "Late",
      chipOrder: "Order",
      chipAdmin: "Admin",
      chipSystem: "System",
      today: "Today",
      yesterday: "Yesterday",
    },
  },
  bn: {
    tabs: {
      available: "পিকআপ",
      active: "চলমান",
      map: "ম্যাপ",
      history: "ইতিহাস",
      profile: "প্রোফাইল",
      home: "হোম",
      myRides: "আমার রাইড",
      account: "অ্যাকাউন্ট",
      notifications: "নোটিফিকেশন",
    },
    bootstrap: {
      text: "রাইডার ওয়ার্কস্পেস প্রস্তুত করা হচ্ছে...",
    },
    common: {
      online: "অনলাইন",
      offline: "অফলাইন",
      language: "ভাষা",
      refresh: "রিফ্রেশ",
      retry: "আবার চেষ্টা করুন",
      signOut: "সাইন আউট",
      allTime: "সব সময়",
      today: "আজ",
      last7Days: "শেষ ৭ দিন",
      allStatus: "সব স্ট্যাটাস",
      delivered: "ডেলিভারড",
      cancelled: "বাতিল",
      customer: "কাস্টমার",
      restaurant: "রেস্টুরেন্ট",
      urgent: "আর্জেন্ট",
    },
    map: {
      eyebrow: "লাইভ পিকআপ ম্যাপ",
      activeRestaurants: (count: number) => `${count}টি সক্রিয় রেস্টুরেন্ট`,
      noActivePickup: "কোনো সক্রিয় পিকআপ নেই",
      zoomIn: "জুম ইন",
      zoomOut: "জুম আউট",
      focusRider: "রাইডার লোকেশন",
      nextRoute: "পরের রুট",
      readyOnly: "শুধু রেডি",
      loadingMap: "রাইডার ম্যাপ লোড হচ্ছে...",
      preparingMap: "পিকআপ ম্যাপ প্রস্তুত হচ্ছে",
      loadingStates: "রেস্টুরেন্ট ও অর্ডার স্টেট লোড হচ্ছে...",
      previewing: (name: string) => `প্রিভিউ: ${name}`,
      dropOffFirst: (name: string) => `আগে ড্রপ: ${name}`,
      suggestedNext: (name: string) => `পরের সাজেশন: ${name}`,
      distanceAway: (state: string, distance: string) =>
        `${state} - ${distance} দূরে`,
      noActiveNearby: "আশেপাশে সক্রিয় পিকআপ নেই",
      emptyHint:
        "অ্যাকসেপ্টেড, প্রস্তুত হচ্ছে, বা রেডি অর্ডার এখানে দেখা যাবে।",
      restaurantLocation: "রেস্টুরেন্ট লোকেশন",
      reachCustomer: "কাস্টমারে পৌঁছান",
      reachRestaurant: "রেস্টুরেন্টে পৌঁছান",
      customerRoute: "কাস্টমার রুট",
      orders: "অর্ডার",
      nextReady: "পরের রেডি",
      readyCount: (count: number) => `${count}টি রেডি`,
      lateCount: (count: number) => `${count}টি লেট`,
      planAhead: "আগে থেকে প্ল্যান করুন",
      orderStates: "অর্ডার স্টেট",
      switchRestaurantHint: "রেস্টুরেন্ট বদলাতে ম্যাপ মার্কারে ট্যাপ করুন",
      previewRoute: "রুট প্রিভিউ",
      openDirections: "ডিরেকশন খুলুন",
      noOrderSelected: "কোনো অর্ডার সিলেক্ট নেই",
      readyNow: "এখন রেডি",
      pickedUp: "পিকড আপ",
      preparing: "প্রস্তুত হচ্ছে",
      almostReady: "প্রায় রেডি",
      minute: "১ মিনিট",
      minutes: (count: number) => `${count} মিনিট`,
      minutesLate: (count: number) => `${count} মিনিট লেট`,
      minutesLeft: (count: number) => `${count} মিনিট বাকি`,
      distanceMeters: (meters: number) => `${meters} মি`,
      distanceKm: (km: string) => `${km} কিমি`,
      statusReady: "রেডি",
      statusPickedUp: "পিকড আপ",
      statusPreparing: "প্রস্তুত হচ্ছে",
      statusAccepted: "অ্যাকসেপ্টেড",
      statusFallback: "অর্ডার",
    },
    signIn: {
      kicker: "ফুডবেলা রাইডার",
      title: "ফোন দিয়ে সাইন ইন করুন",
      subtitle:
        "রেডি পিকআপ, চলমান ট্রিপ আর লাইভ ট্র্যাকিং দেখতে আপনার রাইডার ফোন নম্বর ব্যবহার করুন।",
      phoneLabel: "ফোন নম্বর",
      phonePlaceholder: "01XXXXXXXXX",
      nameLabel: "পূর্ণ নাম (ঐচ্ছিক)",
      namePlaceholder: "রাইডারের নাম",
      sendOtp: "ওটিপি পাঠান",
      sendOtpError: "ওটিপি পাঠানো যায়নি।",
    },
    verify: {
      title: "রাইডার ওটিপি যাচাই করুন",
      subtitle: (phone: string) =>
        `${phone} নম্বরে পাঠানো ৪ ডিজিটের কোড লিখুন।`,
      placeholder: "1234",
      action: "যাচাই করে এগিয়ে যান",
      error: "ওটিপি যাচাই করা যায়নি।",
    },
    active: {
      title: "চলমান ট্রিপ",
      subtitle: "আপনার কাছে থাকা পিকআপ ও ডেলিভারি অর্ডারগুলো।",
      emptyTitle: "কোনো চলমান ট্রিপ নেই",
      emptyText: "লাইভ ট্র্যাকিং শুরু করতে রেডি অর্ডার পিকআপ করুন।",
    },
    available: {
      title: "পিকআপের জন্য প্রস্তুত",
      subtitle: "সাইকেল রাইডারের অপেক্ষায় থাকা অর্ডারগুলো।",
      emptyTitle: "এই মুহূর্তে কোনো পিকআপ নেই",
      emptyOnline: "নতুন রেডি অর্ডার এখানে নিজে থেকেই দেখা যাবে।",
      emptyOffline:
        "আপনি অফলাইন আছেন। নতুন পিকআপ পেতে প্রোফাইল থেকে অনলাইন হোন।",
      locationPending: "কাস্টমারের লোকেশন অপেক্ষমাণ",
    },
    history: {
      title: "সম্পন্ন ইতিহাস",
      subtitle: "পুরোনো ট্রিপ আর ডেলিভারি activity দেখুন।",
      delivered: "ডেলিভারড",
      cancelled: "বাতিল",
      earnings: "ট্রিপ",
      noTripsTitle: "এই ফিল্টারে কোনো ট্রিপ নেই",
      noTripsText: "সম্পন্ন ডেলিভারি দেখতে অন্য স্ট্যাটাস বা তারিখ বেছে নিন।",
      earningLine: "কাস্টমার",
    },
    profile: {
      title: "রাইডার প্রোফাইল",
      today: "আজ",
      last7Days: "শেষ ৭ দিন",
      delivered: "ডেলিভারি",
      vehicle: "যানবাহন",
      riderStatus: "রাইডার স্ট্যাটাস",
      liveTrip: "লাইভ ট্রিপ",
      noActiveLiveTrip: "কোনো লাইভ ট্রিপ নেই",
      activeAssignedOrders: "চলমান অ্যাসাইনড অর্ডার",
      toggleTitle: "নতুন অ্যাসাইনমেন্ট নিন",
      toggleDescription:
        "অনলাইন হলে নতুন রাইডার অ্যাসাইনমেন্ট পাবেন। অফলাইন রাইডারদের ম্যাপ ও ডিসপ্যাচ থেকে লুকানো রাখা হয়।",
      toggleHint: "আপনি বর্তমানে ডিসপ্যাচের জন্য অফলাইন আছেন।",
      toggleWarning: "অফলাইন হওয়ার আগে চলমান অ্যাসাইনড অর্ডারগুলো শেষ করুন।",
      languageTitle: "ভাষা",
      locationPermissionTitle: "লোকেশন পারমিশন প্রয়োজন",
      locationPermissionText:
        "অনলাইনে যেতে লোকেশন দিন, যাতে ডিসপ্যাচ আপনাকে ম্যাপে দেখাতে ও রুট ঠিক করতে পারে।",
      statusUpdateFailed: "স্ট্যাটাস আপডেট ব্যর্থ",
      statusUpdateFailedText: "রাইডার স্ট্যাটাস আপডেট করা যায়নি।",
    },
    orderDetails: {
      unavailable: "এই অর্ডারের বিস্তারিত এখন পাওয়া যাচ্ছে না।",
      acceptFailed: "অ্যাকসেপ্ট ব্যর্থ",
      pickupFailed: "পিকআপ ব্যর্থ",
      deliverFailed: "ডেলিভারি আপডেট ব্যর্থ",
      trackingSwitchFailed: "লাইভ ট্রিপ পরিবর্তন ব্যর্থ",
      acceptFailedText: "অর্ডার গ্রহণ করা যায়নি।",
      pickupFailedText: "অর্ডার পিকআপ করা যায়নি।",
      deliverFailedText: "ডেলিভারি সম্পন্ন করা যায়নি।",
      trackingSwitchFailedText: "লাইভ ট্রিপ পরিবর্তন করা যায়নি।",
      acceptOrder: "অর্ডার গ্রহণ করুন",
      pickUpOrder: "অর্ডার পিকআপ করুন",
      makeLiveTrip: "এটিকে লাইভ ট্রিপ করুন",
      holdToDeliver: "ডেলিভারড দিতে চেপে ধরে রাখুন",
      deliveringNow: "এখন ডেলিভার করছেন",
      inQueue: "সারিতে আছে",
      startThisDelivery: "এই ডেলিভারি শুরু করুন",
      queuedDeliverLocked:
        "এই ডেলিভারিটি সারিতে আছে। বর্তমান ডেলিভারি শেষ করুন, অথবা এটি এখন ডেলিভার করতে শুরু করুন।",
      switchDeliveryTitle: "লাইভ ডেলিভারি পরিবর্তন করবেন?",
      switchDeliveryBody:
        "এই অর্ডারটি আপনার লাইভ ডেলিভারি হবে এবং এর কাস্টমার আপনাকে ম্যাপে দেখবে। বর্তমান ডেলিভারিটি আবার সারিতে চলে যাবে।",
      switchDeliveryConfirm: "ডেলিভারি শুরু",
      switchDeliveryCancel: "বাতিল",
      switchDeliveryFailed: "ডেলিভারি পরিবর্তন করা যায়নি। আবার চেষ্টা করুন।",
      callCustomer: "কাস্টমারকে কল করুন",
      callRestaurant: "রেস্টুরেন্টে কল করুন",
      previewTitle: "প্রিভিউ মোড",
      previewText:
        "এই অর্ডারকে লাইভ ট্রিপ করলে বর্তমান অ্যাপ্রোচ লেগ আর লাইভ ETA দেখতে পারবেন।",
      availableToAccept: "গ্রহণের জন্য প্রস্তুত",
      liveTripActive: "লাইভ ট্রিপ চালু আছে",
      assignedToYou: "আপনার কাছে অ্যাসাইন করা",
      routeHintPreview:
        "এটি শুধু প্রিভিউ। রেস্টুরেন্ট আর কাস্টমারের ড্রপ দেখা যাচ্ছে, কিন্তু বর্তমান অ্যাপ্রোচ লেগ আপনার সক্রিয় অন্য ট্রিপে আছে।",
      routeHintPickedUp:
        "কাস্টমারের ড্রপ সক্রিয় আছে, আর পুরো ট্রিপ বুঝতে রেস্টুরেন্ট থেকে বাড়ির লেগও দেখা যাচ্ছে।",
      routeHintAssigned:
        "পিকআপ এখন সক্রিয় লেগ। রেস্টুরেন্ট, রাইডার আর কাস্টমারের ড্রপ একসাথে দেখা যাচ্ছে।",
      routeHintDefault: "পিকআপ লেগ শুরু করতে অর্ডার গ্রহণ করুন।",
      customerTitle: "কাস্টমার",
      restaurantTitle: "রেস্টুরেন্ট",
      itemsTitle: "আইটেম",
      timelineTitle: "টাইমলাইন",
      currentPickupLeg: "বর্তমান পিকআপ লেগ",
      currentDeliveryLeg: "বর্তমান ডেলিভারি লেগ",
      nextDeliveryLeg: "পিকআপের পরের ডেলিভারি লেগ",
      routeContext: "রেস্টুরেন্ট থেকে বাড়ির কনটেক্সট",
      fullTripEstimate: "পুরো ট্রিপের সময়",
      toCustomer: "কাস্টমারের দিকে",
      toRestaurant: "রেস্টুরেন্টের দিকে",
      openInMaps: "Google Maps-এ খুলুন",
      sharingLive: "লাইভ লোকেশন শেয়ার হচ্ছে",
      tripEta: "ট্রিপ ETA",
      dropAfterPickup: "পিকআপের পর ড্রপ",
      previewDistance: "প্রিভিউ",
      activateToSeeLiveApproach: "লাইভ অ্যাপ্রোচ দেখতে এটি চালু করুন",
      fullTripDropMeta: "ড্রপ সম্পন্ন করতে বাকি আনুমানিক সময় এটি।",
      fullTripPickupMeta: "এতে পিকআপ লেগ আর কাস্টমার ডেলিভারি লেগ দুটোই আছে।",
      syncLive: "লাইভ ট্র্যাকিং সিঙ্কড",
      syncSyncing: "রাইডার লোকেশন সিঙ্ক হচ্ছে",
      syncOffline: "ট্র্যাকিং থেমেছে, আবার চেষ্টা হচ্ছে",
      lastSync: (value: string) => `সর্বশেষ সিঙ্ক ${value}`,
      queuedWaiting: (count: number) =>
        count > 0
          ? `${count}টি লোকেশন আপডেট পাঠানোর অপেক্ষায় আছে`
          : "সর্বশেষ লোকেশন এখন পাঠানো হচ্ছে",
      queuedRetry: (count: number) =>
        `${count}টি কিউড আপডেট পরে আবার চেষ্টা করা হবে`,
      trackingWeakConnection:
        "নেটওয়ার্ক দুর্বল। লাইভ ডেলিভারি আপডেট স্বয়ংক্রিয়ভাবে আবার চালু হবে।",
      trackingPermissionError:
        "লাইভ ডেলিভারি ট্র্যাকিংয়ের জন্য লোকেশন পারমিশন প্রয়োজন।",
      trackingWaitingFirstLocation:
        "এই ডিভাইস থেকে প্রথম লাইভ লোকেশনের জন্য অপেক্ষা করা হচ্ছে।",
      trackingStartError: "এই ডিভাইসে লাইভ লোকেশন চালু করা যায়নি।",
      pickupSavedWaiting:
        "পিকআপ সেভ হয়েছে। প্রথম লাইভ লোকেশনের জন্য অপেক্ষা করা হচ্ছে।",
      riderLocationWarning:
        "রেস্টুরেন্টে যাওয়ার লাইভ অ্যাপ্রোচ দেখতে অনলাইনে থেকে রাইডার লোকেশন চালু রাখুন।",
      warningOfflineAccept:
        "আপনি অফলাইন আছেন। নতুন অর্ডার অ্যাকসেপ্ট করতে প্রোফাইল থেকে অনলাইন হোন।",
    },
    sheet: {
      pullUpForDetails: "বিস্তারিত দেখতে টানুন",
      pullUpToAccept: "ডেলিভারি নিতে উপরে টানুন",
      newOffers: (n: number) => `${n}টি নতুন অফার`,
      activeDeliveries: (n: number) => `${n}টি চলমান ডেলিভারি`,
      youreOnline: "আপনি অনলাইনে আছেন",
      waitingForOrders: "নতুন অর্ডারের অপেক্ষায়…",
      youreOffline: "আপনি অফলাইনে আছেন",
      goOnlineReceive: "অর্ডার পেতে মেনু থেকে অনলাইন হোন",
      goOnlineStart: "ডেলিভারি অফার পেতে মেনু থেকে অনলাইন হোন।",
      newOffersTitle: "নতুন অফার",
      yourDeliveries: "আপনার ডেলিভারি",
      noOrdersTitle: "এখন কোনো অর্ডার নেই",
      noOrdersText: "নতুন অফার এখানে দেখা যাবে। অর্ডার পেতে অনলাইনে থাকুন।",
      distance: "দূরত্ব",
      eta: "সময়",
      collect: "নিতে হবে",
      amount: "মোট",
      timeline: "টাইমলাইন",
      items: "আইটেম",
      navigate: "নেভিগেট",
      navigateToRestaurant: "রেস্টুরেন্টে নেভিগেট",
      setLive: "লাইভ করুন",
      open: "খুলুন",
      accept: "অ্যাকসেপ্ট",
      acceptDelivery: "ডেলিভারি অ্যাকসেপ্ট",
      markPickedUp: "পিকআপ কনফার্ম",
      markDelivered: "ডেলিভারড কনফার্ম",
      cantDeliver: "এই অর্ডার ডেলিভারি করা যাচ্ছে না?",
      orderAmount: "অর্ডার মূল্য",
      collectFromCustomer: "কাস্টমার থেকে নিন",
      assignedAgo: (ago: string) => `অ্যাসাইন হয়েছে ${ago}`,
      justNow: "এইমাত্র",
      minAgo: (m: number) => `${m} মিনিট আগে`,
      hoursAgo: (h: number, m: number) => `${h} ঘণ্টা ${m} মিনিট আগে`,
      veryLate: (m: number) => `অনেক দেরি — ${m} মিনিট লেট, এখনই ডেলিভারি দিন`,
      pickupLate: (m: number) => `পিকআপ ${m} মিনিট লেট — রেস্টুরেন্টে যান`,
      deliveryLate: (m: number) => `ডেলিভারি ${m} মিনিট লেট — দ্রুত কাস্টমারে পৌঁছান`,
      veryLateChip: (m: number) => `অনেক লেট ${m}m`,
      pickupLateChip: (m: number) => `পিকআপ ${m}m লেট`,
      deliveryLateChip: (m: number) => `ডেলিভারি ${m}m লেট`,
      readyInMin: (m: number) => `প্রায় ${m} মিনিটে রেডি`,
      readyAnyMoment: "যেকোনো মুহূর্তে রেডি",
      preparing: "প্রস্তুত হচ্ছে",
      stillPreparing:
        "এখনো প্রস্তুত হচ্ছে — রেডি হলে আপনার টাস্কে চলে আসবে।",
      notAssignedYet: "এই অর্ডার এখনো আপনাকে অ্যাসাইন করা হয়নি।",
      cantDeliverSubtitle:
        "কী হয়েছে জানান। কাস্টমার ও সাপোর্ট টিমকে জানানো হবে, এবং রিফান্ড স্বয়ংক্রিয়ভাবে হ্যান্ডেল হবে।",
      reasonNoResponse: "কাস্টমার সাড়া দেননি",
      reasonWrongItem: "রেস্টুরেন্ট থেকে ভুল আইটেম",
      reasonOther: "অন্য কারণ",
      addNote: "নোট যোগ করুন (ঐচ্ছিক)",
      keepDelivering: "ডেলিভারি চালিয়ে যান",
      submit: "সাবমিট",
      confirmPickupTitle: "পিকআপ কনফার্ম",
      confirmPickupBody: (order: string, rest: string) =>
        `${order} ${rest} থেকে পিকআপ কনফার্ম করবেন?`,
      yesPickedUp: "হ্যাঁ, পিকআপ হয়েছে",
      confirmDeliveryTitle: "ডেলিভারি কনফার্ম",
      confirmDeliveryBody: (order: string) => `${order} কাস্টমারকে ডেলিভারড কনফার্ম করবেন?`,
      yesDelivered: "হ্যাঁ, ডেলিভারড",
      cancel: "বাতিল",
      somethingWrong: "কিছু একটা সমস্যা হয়েছে",
      tryAgain: "আবার চেষ্টা করুন।",
    },
    notif: {
      eyebrow: "রাইডার ইনবক্স",
      title: "নোটিফিকেশন",
      readAll: "সব পড়া হয়েছে",
      emptyTitle: "এখনো কোনো নোটিফিকেশন নেই",
      emptyText: "অ্যাসাইনমেন্ট অ্যালার্ট ও অ্যাডমিন বার্তা এখানে দেখা যাবে।",
      justNow: "এইমাত্র",
      chipLate: "লেট",
      chipOrder: "অর্ডার",
      chipAdmin: "অ্যাডমিন",
      chipSystem: "সিস্টেম",
      today: "আজ",
      yesterday: "গতকাল",
    },
  },
} as const;

export type DeliveryCopy = (typeof copy)["en"];

export function useDeliveryCopy() {
  const language = usePreferencesStore((state) => state.language);
  const setLanguage = usePreferencesStore((state) => state.setLanguage);

  const messages = useMemo(() => copy[language], [language]);

  return {
    language,
    setLanguage,
    copy: messages,
  };
}

export function isBangla(language: AppLanguage) {
  return language === "bn";
}
